# area tags:values to exclude
# source https://wiki.openstreetmap.org/wiki/Overpass_turbo/Polygon_Features

# for ways
NOT_AREA = {
    "area:highway": ["no"],
    "aeroway": ["no", "taxiway"],
    "amenity": ["no"],
    "boundary": ["no"],
    "building:part": ["no"],
    "building": ["no"],
    "craft": ["no"],
    "golf": ["no"],
    "historic": ["no"],
    "indoor": ["no"],
    "landuse": ["no"],
    "leisure": ["no"],
    "man_made": ["no", "cutline", "embankment", "pipeline"],
    "natural": ["no", "coastline", "cliff", "ridge", "arete", "tree_row"],
    "office": ["no"],
    "place": ["no"],
    "public_transport": ["no"],
    "ruins": ["no"],
    "shops": ["no"],
    "tourism": ["no"],
}
IS_AREA = {
    "barrier": ["city_wall", "ditch", "hedge", "retaining_wall", "wall", "spikes"],
    "highway": ["services", "rest_area", "escape", "elevator"],
    "power": ["plant", "substation", "generator", "transformer"],
    "railway": ["station", "turntable", "roundhouse", "platform"],
    "waterway": ["riverbank", "dock", "boatyard", "dam"],
}
IS_AREA_KEY_ANY_VALUE = [
    "area",
    "area:highway",
    "aeroway",
    "amenity",
    "boundary",
    "building",
    "building:part",
    "craft",
    "golf",
    "historic",
    "indoor",
    "landuse",
    "leisure",
    "man_made",
    "natural",
    "office",
    "place",
    "public_transport",
    "ruins",
    "shop",
    "tourism",
]

# list of relation type value to map a relation to an area or a linestring
# other types are mapped to unknown geoemtry type

RELATION_LINESTRING = ["route"]
RELATION_AREA = ["multipolygon", "boundary"]


# Default queries

HIGHWAYS = {
    "ways": True,
    "must_tags": ["highway"],
    "keep_first": False,
    "exclude": {
        "highway": [
            "abandoned",
            "disused",
            "virtual",
            "no",
            "corridor",
            "elevator",
            "escalator",
            "bus_stop",
            "platform",
        ],
        "service": [
            "crossover",
            "yard",
            "spur",
            "siding",
            "irrigation",
            "slipway",
        ],
        "area": ["yes"],
        "type": ["multipolygon"],
    },
    "tags": [
        "access",
        "amenity",
        "area",
        "highway",
        "junction",
        "maxspeed",
        "motorcar",
        "motor_vehicle",
        "oneway",
        "service",
        "vehicle",
    ],
}

BUILDINGS = {
    "ways": True,
    "relations": True,
    "keep_first": False,
    "must_tags": ["building"],
    "tags": [
        "building",
        "amenity",
        "building:flats",
        "building:levels",
        "building:material",
        "building:max_level",
        "building:min_level",
        "building:fireproof",
        "building:use",
        "craft",
        "height",
        "landuse",
        "levels",
        "office",
        "operator",
        "shop",
    ],
}


POIS = {
    "nodes": True,
    "ways": True,
    "keep_first": False,
    "must_tags": ["amenity"],
    "tags": [
        "amenity",
        "arts_centre",
        "atm",
        "bank",
        "bicycle_parking",
        "bicycle_rental",
        "bicycle_repair_station",
        "bar",
        "bbq",
        "biergarten",
        "brothel",
        "cafe",
        "car_rental",
        "car_repair",
        "car_sharing",
        "car_wash",
        "casino",
        "charging_station",
        "childcare",
        "cinema",
        "clinic",
        "college",
        "dentist",
        "doctors",
        "driving_school",
        "drinking_water",
        "fast_food",
        "fire_station",
        "food_court",
        "fountain",
        "fuel",
        "gambling",
        "hospital",
        "ice_cream",
        "internet_access",
        "kindergarten",
        "landuse",
        "language_school",
        "library",
        "music_school",
        "nightclub",
        "nursing_home",
        "office",
        "operator",
        "parking",
        "pharmasy",
        "planetarium",
        "police",
        "post_office",
        "pub",
        "public_bath",
        "rescue_station",
        "restaurant",
        "retirement_home",
        "school",
        "social_centre",
        "social_facility",
        "source",
        "spa",
        "start_date",
        "stripclub",
        "taxi",
        "theatre",
        "university",
    ],
}